form_data = {
			'SignUpWizard_view-current_step': '0',
			'0-username': 'jacob1',
			'0-first_name': 'Jacob',
			'0-last_name': 'Lopez',
			'0-password1': 'hello123',
			'0-password2': 'hello123',
			'0-email': 'jacob@gmail.com',
			'wizard_step': '1',
			'1-weight': 110,
			'1-height_ft': 5,
			'1-height_in': 0,
			'1-goal_weight': 104,
			'1-gender': 'F',
			'1-birth_date': '10/01/1991',
			'1-zip_code': 10005,
			'1-lifestyle': 'S',
			'1-workouts_week': 0,
			'1-min_per_workout': 30,
			'1-goal': 'L2',
			
		}