# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170412_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='net_calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height_in',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(),
        ),
    ]
