# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170414_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeals',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
