# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_userdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdays',
            name='date',
            field=models.DateField(),
        ),
    ]
