# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170419_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermeals',
            name='done',
        ),
    ]
