# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 20:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0008_remove_usermeals_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='RememberMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_food', models.ManyToManyField(to='polls.UserMeals')),
            ],
        ),
    ]
