# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20170606_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RememberMeal',
            new_name='RememberMeals',
        ),
    ]
