# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 22:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20170606_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remembermeals',
            name='user_food',
        ),
        migrations.AddField(
            model_name='remembermeals',
            name='cal_eaten',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='remembermeals',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='remembermeals',
            name='date',
            field=models.DateField(default=datetime.date(2017, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remembermeals',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='remembermeals',
            name='food_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.FoodDatabase'),
        ),
        migrations.AddField(
            model_name='remembermeals',
            name='meal_type',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Snacks')], default='B', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remembermeals',
            name='portion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='remembermeals',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='remembermeals',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='remembermeals',
            name='sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='remembermeals',
            name='units',
            field=models.CharField(default='grams', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remembermeals',
            name='units_consumed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='remembermeals',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
