# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20170606_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretusermeals',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='secretusermeals',
            name='user',
        ),
        migrations.DeleteModel(
            name='SecretUserMeals',
        ),
    ]
